from go_loader import GoLoader
from do_loader import DoLoader
from homolog_loader import HomoLogLoader
from so_loader import SoLoader
from ortho_loader import OrthoLoader
from omim_loader import OMIMLoader
from gene_loader import GeneLoader
from go_gene_annot_loader import GoGeneAnnot
from disease_loader import DiseaseLoader
from aggregate_loader import AggregateLoader
