from go_loader import GoLoader
from homolog_loader import HomoLogLoader
from so_loader import SoLoader
from omim_loader import OMIMLoader
from gene_loader import GeneLoader
from go_gene_annot_loader import GoGeneAnnot
from disease_gene_annot_loader import DiseaseGeneAnnotLoader
from aggregate_loader import AggregateLoader